swagger: '2.0'
info:
  version: '1'
  title: Upload Champ User Enrollments to S3
  description: Stream used for pushing all champ User Enrollments for a locale.
  x-slack: '#ca-data-tech'
produces:
  - application/json
paths:
  /champ.USER_ENROLLMENT:
    get:
      summary: Retrieve all User Enrollments from Oracle for a locale to push to s3.
      description: Retrieve all User Enrollments from Oracle for a locale to push to s3.
      responses:
        '200':
          description: Champ User Enrollments
          schema:
            $ref: '#/definitions/user_enrollment'
definitions:
  user_enrollment:
    type: object
    properties:
      enrollment_id:
        type: integer
        description: Id of each Enrollment for a User
      user_id:
        type: integer
        description: Id of the User
      meeting_user_map_id:
        type: integer
        description: Id of the Meeting User Map table
      enrollment_date:
        type: string
        format: date
        description: Date on which User Enrolls
      fee_paid_flag:
        type: string
        description: Fee is being paid or not
        enum:
             - Y
             - N
      enroll_type_id:
        type: integer
        description: Id of the Enrollment Type
      enroll_action_id:
        type: integer
        description: Id of the Enrollment Action      
      location_id:
        type: integer
        description: Id of the location where the user enrolled
      calculated_date_flag:
        type: string
        description: date is calculated or not
        enum:
             - Y
             - N
      obsolete_flag:
        type: string
        description: Is this record Obsolete or not
        enum:
             - Y
             - N 
      country_id:
        type: integer
        description: Id of the Locale
      created_date:
        type: string
        description: Created DateTime
      created_by:
        type: string
        description: Created By
      last_upd_date:
        type: string
        description: Last Updated DateTime
      last_upd_by:
        type: string
        description: Last Updated By